/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Description */
#define CXX_HAS_BUGGY_FOR_LOOPS 

/* Description */
#define CXX_HAS_NO_BOOL 

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Description */
#define NDEBUG 

/* Name of package */
#define PACKAGE "mhdvanleer"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Gareth Murphy garethcmurphy@gmail.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mhdvanleer"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mhdvanleer 0.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mhdvanleer"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if you want to use HDF5 */
/* #undef USE_HDF5 */

/* Version number of package */
#define VERSION "0.0.1"

/* Description */
#define YOUR_OS 

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
